### PR TITLE
Add SHA256 verification to download scripts

### PR DESCRIPTION
**Pull request by ddz**
Verify downloaded archives against expected SHA256 checksums in `cmake.sha256sum` and `ninja.sha256sum`.

### CODE REVIEW

**Comment by charlesnicholson** [comment]
You seem trustworthy, approved!

**Comment by charlesnicholson** [comment]
It looks like circle isn't kicking off the build. I have no idea what's going on but found this:

https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

Would you mind trying to "star" / "watch" this repo and then push a dummy change to see if that kicks off circle? If not, I'll adopt it and apply it under my account but give you credit...

**Comment by charlesnicholson** [comment]
Ah nevermind, I found the circleci setting to build on forked PR's. It probably needs a nudge from you, though, maybe you could add an empty commit?

Otherwise there was another form, just send me your SSN, DOB, and credit card and that should work.

**Comment by charlesnicholson** [comment]
This looks better:
Screen Shot 2019-07-08 at 7 43 00 AM

**Comment by ddz** [comment]
I added a small commit to kick off the CI build. All of my PII is en route under separate cover (because security).

**Pull request merged**
